server:
  port: 8089
spring:
  application:
    name: mailservice
  zipkin:
    base-url: http://127.0.0.1:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true