server:
  port: 8099
spring:
  application:
    name: mailservice
  zipkin:
    base-url: http://127.0.0.1:9411/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true